### ISSUE TITLE
Sidebar links not working

### ISSUE THREAD

**Issue by test0123** [jungal01/jungal01.github.io#1]
If I open the sidebar and click a link, I get an error, e.g.:

> 404
> 
> File not found
> 
> The site configured at this address does not contain the requested file.
> 
> If this is your site, make sure that the filename case matches the URL.
> For root URLs (like http://example.com/) you must provide an index.html file.
>
> Read the full documentation for more information about using GitHub Pages.

Maybe your index.html is expecting the children to be in a _pages_ directory, but in the actual repo they are at the top level?

**Comment by jungal01** [comment]
I am currently investigating this issue. As of now, this project is low priority, but a fix with a description of the issue will be added within the next 5 days.

**Comment by jungal01** [comment]
The links were failing due to not updating links after changing the file structure. The website is fully functional again.
